// splurge-app/resources/js/components/flash-messages.vue
<template>
  <div :style="rootStyle" class="relative md:w-52">
      <template v-for="item in decoratedMessages" :key="item.id">
          <div :class="getItemClass(item)" class="ease-in clear-both px-4 py-2 w-full rounded mb-2 duration-300 transition-opacity bg-opacity-70">
              <a @click="close(item.id)" class="float-right cursor-pointer hover:font-boldp-2">&times;</a>
              <p v-text="item.message"></p>
          </div>
      </template>
  </div>
</template>

<script>
import {uniqueId} from 'lodash';
export default {
    props: {
        messages: {
            type: Array,
            required: true
        },
        delay: {
            type: Number,
            default: 3000
        }
    },
    data() {
        return {
            decoratedMessages: this.messages.map((m) => {
                return {
                    ...m,
                    closing: false,
                    id: uniqueId("flash_")
                };
            }),
            scrollTop: 0
        };
    },
    computed: {
        rootStyle() {
            return {
                paddingTop: `${this.scrollTop}px`
            };
        }
    },
    mounted() {
        setTimeout(() => {
            this.closeNextImpl();
        }, this.delay);
        this.scrollTop = window.scrollY + 10;
    },
    methods : {
        getItemClass(item) {
            switch (item.type) {
                case 'success':
                    return 'text-white bg-green-800 ' + this.getClosingClass(item);
                case 'warning':
                case 'warn':
                    return 'text-black bg-yellow-500 ' + this.getClosingClass(item);
                case 'danger':
                case 'error':
                    return 'text-white bg-red-700 '  + this.getClosingClass(item);
                default:
                    return 'text-white bg-gray-700 ' + this.getClosingClass(item);
            }
        },
        getClosingClass(item) {
            return item.closing ? 'opacity-10' : 'opacity-100';
        },
        closeNext() {
            this.closeNextImpl();
        },
        closeNextImpl() {
            if (this.decoratedMessages.some(x => x.important !== true)) {
                this.decoratedMessages = this.decoratedMessages.map((item) => {
                    if (!item.closing && item.important !== true) {
                        this.scheduleRemove(item.id);
                        return {
                            ...item,
                            closing: true
                        };
                    }
                    return item;
                });


            }
        },
        close(id) {
            this.decoratedMessages = this.decoratedMessages.map((item) => {
                if (!item.closing && item.id === id) {
                    this.scheduleRemove(item.id);
                    return {
                        ...item,
                        closing: true
                    };
                }
                return item;
            });
        },
        scheduleRemove(id) {
            setTimeout(() => {
                this.decoratedMessages = this.decoratedMessages.filter(x => x.id !== id);
                this.closeNextImpl();
            }, 1000);
        }
    }
}
</script>

// splurge-app/resources/js/v2/components/FlashMessages.tsx
import React, {FC, useState, useRef, useEffect} from "react";

import uniqueId from "lodash/uniqueId";

import classnames from 'classnames';

export interface FlashMessage {
    message: string;
    type: string;
    important?: boolean;
}

interface FlashMessageWithId extends FlashMessage {
    id: string;
    closing: boolean;
}


export interface MessagesProps {
    messages: FlashMessage[];
}

const translateTypeToClass = (type: string): string => {
    switch (type) {
        case 'success':
            return 'bg-green-700 text-white';
        case 'warn':
        case 'warning':
            return 'bg-yellow-700 text-black';
        case 'error':
        case 'fail':
        case 'failure':
            return 'bg-red-700 text-white';
        default:
            return 'bg-gray-700 text-white';
    }


}


const renderer: FC<MessagesProps> = (props) => {
    const [messages, setMessages] = useState<FlashMessageWithId[]>(props.messages.map((m) => {
        return {...m, id: uniqueId('flash_'), closing: false}
    }));

    if (messages.length === 0) {
        return null;
    }

    const closeMessage = (message: FlashMessageWithId): Promise<void> => new Promise((resolve, reject) => {
        if (message.closing) {
            return resolve();
        }
        setMessages(messages.map(m => {
            if (m.id === message.id) {
                return {...m, closing: true};
            }
            return m;
        }));

        setTimeout(() => {
            setMessages(messages.filter(x => x.id !== message.id));
            resolve();
        }, 2000);
    });


    const containerRef = useRef(null);

    const autoCloseAll = () => {
        setTimeout(() => {
            const m = messages.find(x => !x.closing && x.important !== true);
            if (m) {
                closeMessage(m).then(autoCloseAll);
            }
        }, 3000);
    };

    useEffect(() => {
        if (containerRef.current) {
            (containerRef.current as HTMLElement).style.marginTop = `${window.screenTop + 10}px`; 
        }
        autoCloseAll();
    }, []);

    return <div ref={containerRef} className="relative md:w-52">
        {
            messages.map((msg) => (<div key={msg.id} className={classnames('ease-out flex flex-row justify-between items-center rounded px-4 py-2 w-full',
            'rounded mb-2 duration-700 transition-opacity bg-opacity-70', translateTypeToClass(msg.type), {
                'opacity-100': !msg.closing,
                'opacity-0': msg.closing,
            })}>
                <span>
                {msg.message}
                </span>
                <a className="closing" onClick={(e) => {
                    closeMessage(msg);
                }}>
                    &times;
                </a>
            </div>))
        }

    </div>




}


export default renderer;
