// splurge-app/resources/js/v2/components/admin/tags/manager.tsx
import React, { FC, useState, useEffect } from "react";

import Selector, { SelectableTag } from './selector';

import axios from '../../../../axios-proxy';

enum Status {
    idle = 0,
    loading = 1,
    loaded = 2,
    failed = -1,
    updating = 3,
}


interface Taggable {
    id: number;
    type: string;
}
export interface ManagerProps {
    taggable: Taggable,
    baseURL: string;
    indexUrl?: string;
}

const fetchTags = async (url: string, taggable: Taggable): Promise<SelectableTag[]> => {
    const resp = await axios.get<{ data: SelectableTag[] }>(url, {
        params: {
            attachment: '1',
            attachments: '1',
            type_name: taggable.type,
            type_id: String(taggable.id)
        }

    });
    return resp.data.data;
};

const attach = async (tag: SelectableTag, options: { baseUrl: string; taggable: Taggable }) => {
    const resp = await axios.post(`${options.baseUrl}/${tag.id}/attach`, {
        taggable: options.taggable
    });

    return resp.data;
};


const detach = async (tag: SelectableTag, options: { baseUrl: string; taggable: Taggable }) => {
    const resp = await axios.delete(`${options.baseUrl}/${tag.id}/attach`, {
        params: {
            'taggable[id]': options.taggable.id,
            'taggable[type]': options.taggable.type,
        }
    });
    return resp.data;
};

const Manager: FC<ManagerProps> = (props) => {
    const [tags, setTags] = useState<SelectableTag[]>([]);

    const [status, setStatus] = useState(Status.idle);

    useEffect(() => {
        setStatus(Status.loading);
        fetchTags(props.baseURL, props.taggable)
            .then((tags) => {
                setTags(tags);
                setStatus(Status.loaded);
            }, (err) => {
                setStatus(Status.failed);
            });
    }, []);


    const handleSelect = async (tag: { id: number }) => {
        const t = tags.find(u => u.id === tag.id);
        if (!t) {
            return;
        }
        try {
            await attach(t, { baseUrl: props.baseURL, taggable: props.taggable });
            setTags(tags.map((u) => {
                if (u.id === tag.id) {
                    return { ...u, attached: true };
                }
                return u;
            }))
        } catch (error) {

        }
    };

    const handleDelete = async (tag: { id: number }) => {
        const t = tags.find(u => u.id === tag.id);
        if (!t) {
            return;
        }
        try {
            await detach(t, { baseUrl: props.baseURL, taggable: props.taggable });
            setTags(tags.map((u) => {
                if (u.id === tag.id) {
                    return { ...u, attached: false };
                }
                return u;
            }))
        } catch (error) {

        }
    };


    return <div>
        {
            status > Status.idle && (<div className="flex flex-row items-center justify-end bg-white">
                <span className="text-gray-700 mr-8">Tags:</span>
                <Selector tags={tags} inputName="tags" onSelect={handleSelect} onRemove={handleDelete} />
            </div>)
        }

    </div>

}

export default Manager;

// splurge-app/resources/js/components/admin/tags/manager.vue
<template>
  <div v-if="loaded" class="flex flex-row items-center justify-end bg-white">
      <span class="text-gray-700 mr-8">Tags:</span>
      <Selector :tags="tags" :input-name="'tags'" @added="attach" @removed="detach" />
      <svg xmlns="http://www.w3.org/2000/svg" v-if="busy" class="mx-4 h-6 w-6 animate-spin" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
        </svg>
      <a v-if="indexUrl" :href="indexUrl" class="link ml-8">
          Manage list of tags
      </a>
  </div>
</template>

<script>
import Selector from './selector';
import axios from 'axios';
const Api = axios.create({
    withCredentials: true,
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
    },
    transformRequest: (data, headers) => {
        const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        if (data) {
            data['_token'] = token;
            return JSON.stringify(data);
        }
        const d = {
            _token: token
        };
        return JSON.stringify(d);
        
    }
});
export default {
    components: {Selector},
    props: {
        taggable: {
            type: Object,
        },
        indexUrl: String,
        baseURL: {
            type: String,
            required: true
        }
    },
    data() {
        return {
            tags: [],
            showSelect: false,
            selectedTag: null,
            busy: false,
            errorMessage: null,
            loaded: false
        };
    },
    mounted() {
        this.fetch();
    },
    methods : {
        choose() {
            this.showSelect = true;
        },
        async attach(tag) {
            this.busy = true;
            try {
                await Api.post(`${this.baseURL}/${tag.id}/attach`, {
                    taggable: this.taggable
                });
                this.tags = this.tags.map((t) => {
                    if (t.id === tag.id) {
                        return {...t, attached: true, taggable: this.taggable};
                    }
                    return t;
                });
            } catch (ex) {
                this.errorMessage = ex.message;
            } finally {
                this.busy = false;
            }
        },
        async detach(tag) {
            this.busy = true;
            try {
                await Api.delete(`${this.baseURL}/${tag.id}/attach`, {
                    params: {
                        'taggable[id]': this.taggable.id,
                        'taggable[type]': this.taggable.type,
                    }
                });
                this.tags = this.tags.map((t) => {
                    if (t.id === tag.id) {
                        return {...t, attached: false, taggable: null};
                    }
                    return t;
                });
            } catch (ex) {
                this.errorMessage = ex.message;
            } finally {
                this.busy = false;
            }
        },
        async fetch() {
            const resp = await Api.get(this.baseURL, {
                params: {
                    attachment: '1',
                    attachments: '1',
                    type_name: this.taggable.type,
                    type_id: String(this.taggable.id)
                }
            });
            this.tags = resp.data.data;
            this.loaded = true;
            
        }
    },
    computed: {
        attached() {
            return this.tags.filter(x => x.attached === true);
        },
        available() {
            return this.tags.filter(x => x.attached !== true);
        }
    }
}
</script>

<style>

</style>
