// splurge-app/resources/js/components/forms/horizontal-container.vue
<template>
  <div class="form-group" :class="{'error': hasError}">
      <div class="label-wrapper">
          <slot name="label">
              <label class="control-label" v-text="label"></label>
          </slot>
      </div>
      <div class="control-wrapper"><slot></slot> </div>
  </div>
</template>

<script>
export default {
    props : {
        label: String,
        hasError: Boolean
    },
}
</script>

// splurge-app/resources/js/v2/components/forms/horizontal-container.tsx
import React, {FC} from "react";
import isString from "lodash/isString";
export interface ContainerProps {
    label: any;
    className?: string;
}

const Container: FC<ContainerProps> = (props) => (<div className={`form-group ${props.className || ''}`}>
     <div className="label-wrapper">
          {
              isString(props.label) && (<label className="control-label">
                  {props.label}
              </label>)
          }
          {
              !isString(props.label) && (<>{props.label}</>)
          }
      </div>
      <div className="control-wrapper">{props.children}</div>

</div>);


export default Container;
